service: sf-assignment-pow
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  memorySize: 256
  logRetentionInDays: 14
  timeout: 900
  environment:
    BLOCKCHAIN_API_BASE_URL: https://blockchain.info
    ENERGY_PER_BYTE_KWH: "4.56"
   

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node18
    watch:
      pattern: ['src/**/*.ts']

functions:
  graphql:
    handler: src/fn_graphql.handler
    events:
      - httpApi: '*'
