service: sf-assignment-pow
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 512  
  logRetentionInDays: 14
  environment:
    BLOCKCHAIN_API_BASE_URL: https://blockchain.info
    ENERGY_PER_BYTE_KWH: "4.56"
    NODE_OPTIONS: "--enable-source-maps"  
   

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node18
    watch:
      pattern: ['src/**/*.ts']

functions:
  graphql:
    handler: src/fn_graphql.handler
    memorySize: 512           
    reservedConcurrency: 100  
    provisionedConcurrency: 2 
    events:
      - httpApi: '*'
    environment:
      GRAPHQL_INTROSPECTION: ${opt:stage, 'dev'}
      GRAPHQL_PLAYGROUND: ${opt:stage, 'dev'}

